// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAdwU29ZGKJcu4U2CSW0UsLbr2ApzXIw',
    appId: '1:442906012491:android:ef1679b5280029157b96ce',
    messagingSenderId: '442906012491',
    projectId: 'flutter-insta-clone-yofardev',
    storageBucket: 'flutter-insta-clone-yofardev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrc_SC8d4HPJyGl3upD0CWIrKd-JJm3_8',
    appId: '1:442906012491:ios:3c11723b33f3653e7b96ce',
    messagingSenderId: '442906012491',
    projectId: 'flutter-insta-clone-yofardev',
    storageBucket: 'flutter-insta-clone-yofardev.firebasestorage.app',
    androidClientId: '442906012491-hnufchr6clfvi5uojvk9aj5i34po32v8.apps.googleusercontent.com',
    iosClientId: '442906012491-u81qcj1bq0tffc65qei7ad1j8gfb6pvp.apps.googleusercontent.com',
    iosBundleId: 'fr.yofardev.flutterInstagramClone',
  );

}